### PR TITLE
Fix for ActiveRecord dirty attributes for rails 5.2

### PR DESCRIPTION
**Pull request by madding**
Cause of bug: 
https://github.com/rails/rails/issues/33753#issuecomment-417503496
You cannot call attribute_will_change! on something not registered with the attributes API -- There must be attribute :user_ids if you want that to be managed by Active Record.

For fixing this I added instantce variable where store  changed attributes after save.

### CODE REVIEW

**Comment by madding** [comment]
@justincampbell I left only the necessary changes

**Comment by madding** [comment]
I rebased branch

**Comment by justincampbell** [comment]
@madding Thanks for keeping this updated! I wasn't able to allocate time to get Rails 5.2 support into the 0.5.0 release, but I hope to find time to review this and get another release out soon. Thanks for your patience!

**Comment by dankozlowski** [comment]
Hey @justincampbell What's the ETA here?  This merge is blocking use of the gem for us.  Can I help?

**Comment by Valarissa** [comment]
#67 was merged. Do you feel like that PR handles all the issues put forth in this PR, or do you feel like something in that PR misses something in your PR @madding ? If it does, then may I close this PR? If it doesn't, would you be able to elaborate what?

Thanks in advance, and sorry for leaving this to languish for so long.

**Comment by madding** [comment]
@Valarissa I think you can close my PR. Yesterday was PRs birthday :)

**Pull request closed without merging**
