### PR TITLE
add comma before serialize in README

### PR DESCRIPTION
**Pull request by kisakov**
Hi. 
I've just added the comma in README because without it I have an error
```
syntax error, unexpected ':', expecting keyword_end
    serialize: :json
```

### CODE REVIEW

**Comment by sgerrand** [comment]
👋 @evanphx: Are you able to review this change?

**Comment by justincampbell** [comment]
Thanks!

**Comment by justincampbell** [comment]
@kisakov Hey! Sorry for the long delay for someone to get to this. I'd love to merge this if you can first sign the CLA at https://cla.hashicorp.com/hashicorp/vault-rails?pullRequest=55 Thanks!

**Comment by kisakov** [comment]
@justincampbell I signed the CLA. Thank you.

**Pull request merged**
