### PR TITLE
feature - run time evaluated keys

### PR DESCRIPTION
**Pull request by dkaffee92**
motivation for this:
allow creating keys based on rules rather on column, perhaps creating a key per user or sharing keys among models.

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @dkaffee92 

The reason we do not support this in vault-rails is because this would likely crumble your Vault instance by having a unique key for each row in the database. Vault's transit backend is designed for lightweight data, but if Vault needs to manage 100,000 decryption keys (one for each row in the database), it would be very painful for the Vault server.

Since each path in the transit backend would be creating a new key, Vault would effectively be generating a unique key for each user (as you specified in your description), but that is not really a support pattern in Vault at this time. 

If you would like to share keys across multiple models, you can still specify the `key` value as a string or symbol.

Does that make sense?

**Comment by dkaffee92** [comment]
Hi @sethvargo, thank you for your time,

Let's examine two different use cases,
The first one is that you have a number of keys, a low sum of keys that you use within the application, for instance 10, and when a value is decrypted you need to decide in run-time which one to use. In that case evaluation the code makes sense and that's a use case.

The second use case is per user encryption.
Now let's leave network IO out of the equation because if I encrypt with 1 key a million times or with millions keys 1 time each it's the same network I/O.
Now we also need to leave CPU I/O because it depends on how golang itself does encryption/decryption and it still doesn't matter the amount of keys.

So we're basically looking at the read/write operations vault has to do from the physical backend, leaving aside inmem and file, we have consul, etcd, zk, s3 and mysql.
All are proven technologies which can work under load and storing a few hundred thousands or even millions of rows is not problematic.

Consul for example, as you know (pretty cheeky to think I can lecture you about consul :-) ), is using boltdb, which works great for read intensive workloads and the size of keys is meaningless as it is.

Zookeeper is can handle tens to hundred of thousands of reads per second, same goes for the other backends.

So the bottleneck is actually encrypt/decrypt, which by definition is heavy on the CPU and vault does not try to solve it.

But you can also mitigate that problem by having strong machines and a lot of them if that's the problem.

Let me know what you think and if my thought process is wrong.

**Comment by sethvargo** [comment]
Hi @dkaffee92 

Thank you for your reply.

> The first one is that you have a number of keys, a low sum of keys that you use within the application, for instance 10, and when a value is decrypted you need to decide in run-time which one to use. In that case evaluation the code makes sense and that's a use case.

In this case, I think this may be a conflation of concerns. Vault should be handling the key rotation and all aspects of key generation, retirement, and validation. That should not be an application concern. Vault 0.1.2 will have built-in support for key rotation like you've described, so I don't think this is a use case that Vault Rails should tackle - it's just part of Vault's default behavior.

Hi @dkaffee92 

The bottleneck, as I understand it, is not the encryption/decryption, but rather the storage of that many decryption keys. I'll let @armon chime in more. We have plans to support something like this in Vault, but we haven't fully scoped it out yet.

At a high level, it's very clear that _you_ understand the implications and have thought through the various edge cases of implementing per-user encryption. However, I am very hesitant to add something like this to vault-rails because it would be _trivially easy_ to kill Vault on any reasonably-sized web application. While I agree that per-row encryption keys are something we definitely want to support in the future, I think there are optimizations in Vault that need to take place before we are able to leverage them in Vault Rails at this time. I realize this is a crappy answer, so I'm going to wait for @armon to chime in.

**Comment by dkaffee92** [comment]
@sethvargo that's an excellent answer and I do think that there could be some optimizations that there can be done,
regarding the first use case, I think I'm misunderstood :-)
It's not key rotation I am talking about, I'll give an even better example.
Let's say that I have a company with a few employees, I would like all the employees to see everyone's secrets but I would not want other companies to have my companies secret (key), so all companies would need their own secret, 
my column is `encrypted_value` and my keys are 
```
application_secrets_company_a_encrypted_value
application_secrets_company_b_encrypted_value
application_secrets_company_c_encrypted_value
application_secrets_company_d_encrypted_value
```
With a proc I can do something of the sort of
```ruby
-> (user) { "application_secrets_company_#{user.company.to_s}_encrypted_val" }
```

I assure you that this is a firm use case, as it actually comes out of a need.

**Comment by armon** [comment]
@dkaffee92 Take a look at the "per-transaction derived key" feature of Vault 0.2. (https://www.hashicorp.com/blog/vault-0-2.html) That is exactly suited for this use case as it minimizes the number of stored keys, while still allowing many unique keys to be used.

**Comment by sethvargo** [comment]
Hi @dkaffee92 

Have you had a chance to look at the derived key format yet?

**Comment by dkaffee92** [comment]
@sethvargo Hi Seth,
I haven't :-( Too much work :+1:

I guess you can close this PR and when we'll need this again we will look at derived keys.

Regards,

**Pull request closed without merging**
